# Line indentation must be 2 spaces (no tabs).
production:
  adapter: {{DB_ADAPTER}}
  encoding: {{DB_ENCODING}}
  reconnect: false
  database: {{DB_NAME}}
  host: {{DB_HOST}}
  port: {{DB_PORT}}
  username: {{DB_USER}}
  password: '{{DB_PASS}}'
  pool: {{DB_POOL}}
  {{DB_SSL_MODE}}
